name = "TemperatureSensors"
uuid = "4e0911ad-eb89-46c3-895a-ce894798b498"
authors = ["Eduardo-BDMAlves <eduardo.alves@polo.ufsc.br>"]
version = "1.0.0-DEV"

[deps]
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Polynomials = "4"
julia = "1.9"
